### ISSUE TITLE
Exploration of the economics data

### ISSUE THREAD

**Issue by andkov** [kse-ua/ua-de-center#15]
# Task

Develop a series of graphs that describe the available data assets that deal with economic indicators. Specifically, work with the product of the `./manipulation/ellis-economics.R` (which digests[ App 3. Показники  фінансвої спроможності тергромад 1 кв 2022 (в ІАС](https://docs.google.com/spreadsheets/d/1F2d9EEx46llTMEFtgotzIRmDD0fx9sia/edit?usp=sharing&ouid=106674411047619625756&rtpof=true&sd=true) ) We don't know yet what those graphs will look like, but we want to:

- [ ] look at univariate distribution of each indicator
- [ ] look at bivariate distributions among indicators
- [ ] look at how indicators change with time
- [ ] how oblasts and regions vary among each other

# Notes:

1. Use `./analysis/economic-outcomes/economic-outcomes.R` as the starting point. 
2. Store work in `./analysis/economic-outcomes/economic-outcomes-yourname.R`  script, I will integrate successful compositions in the main script  `./analysis/economic-outcomes/economic-outcomes.R` .
3. Do not commit graphs
4. See [this commit](https://github.com/kse-ua/ua-de-center/commit/3957af753249b18a42e4a1cdc6b88b8aa2c3e12b) for an example.
5. Contain each graph in a dedicated chunk (e.g. `graph-2`)
